### ISSUE TITLE
Broken loaders turn into beacons.

### ISSUE THREAD

**Issue by branford19** [OmerBenGera/WildLoaders#5]
Hi!

This plugin currently has an issue when running Paper (1.16.5). Whenever loaders are broken, they turn into beacons.

`[06:55:29 ERROR]: Could not pass event BlockBreakEvent to WildLoaders v0.3.2-Beta
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_16_R3.WorldServer.removeEntity(WorldServer.java:1478) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.WorldServer.removePlayer(WorldServer.java:1498) ~[patched_1.16.5.jar:git-Paper-457]
        at com.bgsoftware.wildloaders.nms.ChunkLoaderNPC_v1_16_R3.die(ChunkLoaderNPC_v1_16_R3.java:61) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.NPCHandler.killNPC(NPCHandler.java:58) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoader$0(LoadersHandler.java:91) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:176) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoader(LoadersHandler.java:91) ~[?:?]
        at com.bgsoftware.wildloaders.loaders.WChunkLoader.remove(WChunkLoader.java:109) ~[?:?]
        at com.bgsoftware.wildloaders.listeners.BlocksListener.handleLoaderBreak(BlocksListener.java:100) ~[?:?]
        at com.bgsoftware.wildloaders.listeners.BlocksListener.onLoaderBreak(BlocksListener.java:63) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:91) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityPlayer.tick(EntityPlayer.java:452) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.World.a(World.java:887) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:531) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1357) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:832) [?:?]`

If there's any other details you require, please let me know.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
Any news?

**Comment by branford19** [comment]
Hi,

Sorry for the slow response, this fix works.

Thanks so much for your time!

**Comment by OmerBenGera** [comment]
Perfect, great to hear!
